---

- hosts: all
  become: true
  #tasks:

#  vars:
#    myurl: "https://dlcdn.apache.org/maven/maven-3/3.8.6/source/apache-maven-3.8.6-src.tar.gz"
#    myurltomcat: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.69/bin/apache-tomcat-9.0.69.tar.gz"

#  - name: extractor presents
  vars:
    myurl: "https://dlcdn.apache.org/maven/maven-3/3.8.6/source/apache-maven-3.8.6-src.tar.gz"
    myurltomcat: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.69/bin/apache-tomcat-9.0.69.tar.gz"    

  tasks:   
  - name: extractor presents
    ansible.builtin.yum:
      name:
        - unzip
        - tar
      state: present

  - name: extract archive maven
    ansible.builtin.unarchive:
      src: "{{ myurl }}"
      dest: "/opt/"
      remote_src: true
      validate_certs: true

  - name: extract archive apache tomcat
    ansible.builtin.unarchive:
      src: "{{ myurltomcat }}"
      dest: "/opt/"
      remote_src: true
      validate_certs: true

#  - name: Update path for maven use
    #lineinfile:    
     # line: export PATH=/opt/apache-maven-3.1.1/bin:$PATH
#    shell: export PATH=/opt/apache-maven-3.8.6/bin:$PATH
#      dest: ~/.bashrc
     # args:
      #  executable: /bin/bash
